server:
  port: 4000
#Redis cache 过期时间设置
redis:
  cache:
    expiration: 3600

# sleuth配置
spring:
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.2

# 分库分表支持
sharding:
  jdbc:
    defaultDataSourceName:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123
      jdbc-url: jdbc:mysql://127.0.0.1:3306/tpsix?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    datasource:
      names: ds
      ds:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123
        jdbc-url: jdbc:mysql://127.0.0.1:3306/tpsix?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    config:
      sharding:
        tables:
          sys_log:
            actual-data-nodes: ds.sys_log_${0..1}
            table-strategy:
              inline:
                sharding-column: id
                algorithm-expression: sys_log_${id % 2}
            key-generator-column-name: id


fdfs:
  file-host: http://127.0.0.1:22121/
  tracker-list:
    - 127.0.0.1:22122

qiniu:
  accessKey: hM2cBDEM0FTYzpXbigRW90kV12NhhzhFM3jCzurJ
  secretKey: ENC(HM/K0KmtFoZSBhGDEA0Ez71ePTncZlQ954DfLNMZuOftKZq+2WR+dCXH9QEsf768q9wwd92RXLE=)
  bucket: pigcloud
  qiniuHost: http://p0hpm86wj.bkt.clouddn.com/
